### ISSUE TITLE
LZ77 not fully supported/compatible

### ISSUE THREAD

**Issue by AeonSake** [Venomalia/AuroraLib.Compression#1]
Great library but while I was attempting to parse some LZ77-compressed files, I noticed that your current LZ77 implementation only works on non-chunked data (i.e, byte `0x04` is `0x10`). Nintendo also uses a variant of this algorithm for bigger files (found in some Nintendo DS games) that has `0xf7` in that byte position, followed by a set of chunk sizes. Compression is then executed on each individual chunk, rather than the entire data stream.

```
u8[4] "LZ77" as ASCII string
u8    compression type; 0x10 for single-chunk, 0xf7 for multi-chunk
u16   uncompressed file size

if type is 0x10:
handle the data as single LZ10 chunk

if type is 0xf7:
u8     flags
u16[n] list of chunk end positions
u8     always 0x10 (maybe denoting the chunk compression type as LZ10?)
u32    buffer size
```

Your current implementation is basically just a LZ10 wrapper for the normal single-chunk variant, compressing all data as a single LZ10 block. It would be great to have the multi-chunk variant also implemented in this library as I don't see many other libraries (if any at all) having this implemented properly.

As a reference implementation you could look at [Cuyler36's ACWW Editor](https://github.com/Cuyler36/Animal-Crossing-Text-Editor/blob/master/Animal%20Crossing%20Text%20Editor/Compression/LZ77.cs) which seems to work properly.

**Comment by Venomalia** [comment]
Thanks for the suggestion, I am always interested in expanding the library.
There are so many modifications and this one was unknown to me, I am happy to add it.

Do you perhaps have a test file?

**Comment by AeonSake** [comment]
Sure. I attached a ZIP archive containing a compressed (original) and a decompressed (my implementation) version of a file. GitHub wouldn't let me upload the files directly.

[obj_etc_fish.zip](https://github.com/user-attachments/files/16995311/obj_etc_fish.zip)

**Comment by Venomalia** [comment]
This should support the chunked type.
I have changed the logic a bit because I assume that it was not completely correct.

**Comment by AeonSake** [comment]
Great work! Compression and decompression now works perfectly. Only the `IsMatch()` method is still only checking for the single-chunk variant.

**Comment by Venomalia** [comment]
Oh right! I have corrected it. 👍

**Comment by AeonSake** [comment]
Perfect! I tested it with all random LZ77 files I had around and it worked for all of them. However, I noticed that the files are not quite bit-perfect comparable; it looks like there is something just slightly wrong:
<img width="934" alt="Screenshot 2024-09-14 193529" src="https://github.com/user-attachments/assets/34f20270-7c7b-4a6a-b6a5-0c9c05510996">
(left decompressed+compressed, right original)

I have not tested whether this would cause any issues in an actual game engine.

**Comment by Venomalia** [comment]
It is not unusual that the compressed data is not completely the same, this comes from the selected settings and some small optimizations.
If you encounter problems, it is usually enough to deactivate the `LookAhead` setting.

**Comment by AeonSake** [comment]
Disabling the `LookAhead` option results in an almost entirely different binary output (from a compression standpoint) so I feel like the original file was compressed with a look-ahead algorithm. But I don't think it would cause any issues. Anyways, great (and fast!) work on the LZ77 implementation. I will most likely replace all my hand-rolled compression logic with this library.

**Comment by Venomalia** [comment]
In your example decompressed+compressed is also one byte smaller, better compression offers advantages for mods.
`LookAhead` improves the compression, but the decoder must also support this option, all other options are always safe.

**Comment by AeonSake** [comment]
Hate to bump a closed issue but would it be possible to get a version bump / NuGet update? Much appreciated.

**Comment by Venomalia** [comment]
No problem, I wanted to add a few small algorithms today before I do that.
