### ISSUE TITLE
Possibility to Decompress into a memorystream 

### ISSUE THREAD

**Issue by cl-oalami** [Venomalia/AuroraLib.Compression#6]
Hello there, so i have my code as follows:

```C#
//Check if file can be decompressed
            Stream source = new FileStream(textfile, FileMode.Open, FileAccess.Read, FileShare.Read);
            Stream destination = new MemoryStream();
            if (new LZ10().IsMatch(source))
            {
                //Decompress the file file
                new LZ10().Decompress(source, destination);
            }
            else
                destination = source;
```

But sadly it just outputs the following exception when i try to decompress: System.IO.EndOfStreamException: 'Cannot read System.SByte is beyond the end of the stream.'

I surely don't want to decompress into a file directly by using a FileStream, i just want to use the decompressed data and dispose of the stream when that's over.

Thank you for your guidance and for the beautiful source code.

**Comment by cl-oalami** [comment]
I actually managed to circumvent this by just resetting the position on source to 0 using `seek()`

The working code is now:
```c#
            //Check if file can be decompressed
            Stream source = new FileStream(textfile, FileMode.Open, FileAccess.Read, FileShare.Read);
            Stream destination = new MemoryStream();
            try
            {
                if (new LZ10().IsMatch(source))
                {
                    //Decompress the file file
                    source.Seek(0, SeekOrigin.Begin);
                    new LZ10().Decompress(source, destination);
                }
                else
                {
                    source.Seek(0, SeekOrigin.Begin);
                    source.CopyTo(destination);
                }
            }
            finally
            {
                source?.Dispose();
            }
```

**Comment by Venomalia** [comment]
This is how the IsMatch() currently works, it shifts the position of the source when reading.
Perhaps it makes sense to communicate this more clearly in the documentation?

**Comment by cl-oalami** [comment]
> Perhaps it makes sense to communicate this more clearly in the documentation?

No it is, maybe i misread somewhere, but normally if the IsMatch() shifts the stream, it should logically either reset the position to 0, or the compress/decompress algo should do it, since there is no way to decompress/compress only a part of a stream unless we copyto a specific range of bytes to a new stream, don't you think ? i hope it's possible but i might have missed something in the documentation.

**Comment by Venomalia** [comment]
I made it so that IsMatch no longer changes the position.
I have not changed anything in compress/decompress, there are cases where it is necessary to use the current positon.
